uthread_main: uthreads.h  uthreads.c sleeping_list.c ready_queue.c main.c
	gcc -Wall -Wextra -Wvla -std=gnu99  uthreads.h uthreads.c sleeping_list.h sleeping_list.c ready_queue.h ready_queue.c main.c -o main
